//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClothesForHands.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialSupp = new HashSet<MaterialSupp>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public int TypeId { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
        public int MinCount { get; set; }
        public int CountInBox { get; set; }
        public int TypeDimension { get; set; }

        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual UntType UntType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSupp> MaterialSupp { get; set; }
    }
}
